# FILTERING
min_ratio: .1 # to be set to -1 to switch off min_ratio filtering
min_read: 9 # to be set to -1 to switch off min_read filtering
edit_distance_3p: 3 # to be set to -1 to switch off 3p filtering
edit_distance_5p: 2 # to be set to -1 to switch off 5p filtering

# DISPLAY
display_summary: True
display_sequence_info: True
display_nucleotide_dist: True
display_group_output: True

# AMBIGUOUS LETTERS
ambiguous_letters: True

# DESTRUCTIVE MOTIF PULL
destructive_motif_pull: False

# INPUT
data: 'data' # path to folder containing input files
motif_consensus_file: 'motif-consensus.fa'
reference_file: 'miRBase21-master.tsv'
mirbase_version: '21' # version of miRBase being used for reference files
source_ontology: 'miRBase v21 doi:10.25504/fairsharing.hmgte8'

# OUTPUT
group_output_name: 'cohort1'

# DISTANCE METRIC
deletion_score: 1
insertion_score: 1
substitution_AG: 1 # transition
substitution_GA: 1 # transition
substitution_CT: 1 # transition
substitution_TC: 1 # transition
substitution_AT: 1 # transversion
substitution_TA: 1 # transversion
substitution_AC: 1 # transversion
substitution_CA: 1 # transversion
substitution_GC: 1 # transversion
substitution_CG: 1 # transversion
substitution_GT: 1 # transversion
substitution_TG: 1 # transversion
